# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
maven_group=red.jackf
archive_name=jsst
# also used in publish action
mod_version=2.1.1

deps.fabric_loader=0.16.10
deps.mixinextras=0.5.0-beta.5

deps.minecraft=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.yacl=[VERSIONED]
deps.jackfredlib=[VERSIONED]
deps.servertranslations=[VERSIONED]
deps.sgui=[VERSIONED]

# Project Settings
# GitHub URL with no trailing slash
project.curseforge_id=850725
project.curseforge_slug=jsst
project.modrinth_id=eiYW74Yj
project.release_name=JSST
project.github_url=https://github.com/JackFredMods/JacksServerSideTweaks
project.github_repo=JackFredMods/JacksServerSideTweaks

# used for minecraft versions, since snapshots are different on CR/MR
project.curseforge_versions=[VERSIONED]
project.modrinth_version=[VERSIONED]

project.dry_run=false